---
roles:
  - name: githubixx.ansible_role_wireguard
    src: https://github.com/gavmain/ansible-role-wireguard
    version: githubixx_wg_amzn_2
  - name: gavmain.ansible-role-wireguard-ssm
    src: https://github.com/gavmain/ansible-role-wireguard-ssm
    version: v1.0.0
  - name: gavmain.ansible-role-update-route53-onboot
    src: https://github.com/gavmain/ansible-role-update-route53-onboot
    version: enable_at_boot_fix

  # Will be re-instated once the PR has been accepted
  # - name: githubixx.ansible_role_wireguard
  #   version: 7.8.0

collections:
  - name: amazon.aws
    version: 1.4.0
  - name: community.aws
    version: 1.3.0
