---
roles:
  - name: gavmain.wireguard-configuration
    src: https://github.com/gavmain/ansible-role-wireguard-configuration
    version: v1.0.0

collections:
  - name: amazon.aws
    version: 3.3.1
