---
- name: Install dependencies
  yum:
    name: "{{ update_dns_rpm_deps }}"
    state: present
  vars:
    ansible_python_interpreter: /usr/bin/python

- name: test config file
  template:
    src: usr/local/etc/test.cfg.j2
    dest: /usr/local/etc/test.cfg
#   notify:
#     - restart update-dns.service

- name: Install the update-dns.sh script
  copy:
    src: usr/local/sbin/update-dns.sh
    dest: /usr/local/sbin
    mode: 0755
    owner: root
    group: root
  notify: restart update-dns.service

- name: Install the update-dns.service file
  copy:
    src: etc/systemd/system/update-dns.service
    dest: /usr/local/sbin
    mode: 0755
    owner: root
    group: root
  notify: systemd daemon reload

- name: enable the update-dns.service daemon
  service:
    name: update-dns.service
    enabled: yes

